# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: regcred
# spec:
#   refreshInterval: "0"
#   secretStoreRef:
#     name: vault
#     kind: ClusterSecretStore
#   target:
#     name: regcred
#     template:
#       type: kubernetes.io/dockerconfigjson
#     creationPolicy: Owner
#   dataFrom:
#   - extract:
#       key: secrets/regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.spec.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      # imagePullSecrets:
      # - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80