apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 {{- range .Values.ingress.tls }}
  {{- range .hosts }}
  name: "letsencrypt-le-prod-{{ . }}"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: "le-prod-{{ . }}"
    solvers:
    - http01:
       ingress:
         podTemplate:
             spec:
              nodeSelector:
                beta.kubernetes.io/os: linux
         class: nginx
         {{- end }}
     {{- end }}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
 {{- range .Values.ingress.tls }}
  {{- range .hosts }}
  name: "le-prod-crt-{{ . }}"
spec:
  secretName: "secret-le-prod-{{ . }}"
  issuerRef:
    name: "letsencrypt-le-prod-{{ . }}"
    kind: Issuer
  commonName: "{{ . }}"
  dnsNames:
    - "{{ . }}"
  {{- end }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
 {{- range .Values.ingress.tls }}
  {{- range .hosts }}
  name: "ingress-tls-{{ . }}" 
spec:
  tls:
  - hosts:
      - {{ . | quote }}
    secretName: "secret-le-prod-{{ . }}"
  rules:
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy
            port: 
              number: 80
        {{- end }}
        {{- end }}
