apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:

  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"

  name: greeting-ingress

spec:
  tls:
  - hosts:
    - todo-dev-test.conix.ai
    secretName: echo-tls
    
  
  rules:
  - host: todo-dev-test.conix.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: proxy
            port: 
              number: 80




