apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-le-prod-redis-dev-test

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory 
    privateKeySecretRef:
      name: le-prod-redis-dev-test
    solvers:
    - http01:
       ingress:
         podTemplate:
             spec:
              nodeSelector:
                beta.kubernetes.io/os: linux
         class: nginx
