apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 {{- range .Values.ingress.tls }}
  {{- range .hosts }}
  name: "issuer-prod-{{ . }}"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef: 
      name: "pk-prod-{{ . }}"
    solvers:
    - http01:
       ingress:
         podTemplate:
             spec:
              nodeSelector:
                beta.kubernetes.io/os: linux
         class: nginx
         {{- end }}
     {{- end }}