apiVersion: v1
kind: PersistentVolume
metadata:
  {{- range .Values.ingress.host }}
  name: "pv-mongo-{{ . }}"
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.persistent.storage.size }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
  {{- range .Values.ingress.host }}
    path: "/data/mongodb-{{ . }}"
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  {{- range .Values.ingress.host }}
  volumeName: "pv-mongo-{{ . }}"
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistent.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: pvc-mongo
          
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017