apiVersion: v1
kind: PersistentVolume
metadata:
  name: "pv-mongo-{{ .Values.branch.name }}"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.storage.size }}
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mongodb-{{ .Values.branch.name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: "pv-mongo-{{ .Values.branch.name }}"
  resources:
    requests:
      storage: {{ .Values.storage.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: mongo-data
            mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: pvc-mongo
          
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017