apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: regcred
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: regcred
    template:
      type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secrets/regcred
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  {{- range .Values.ingress.host }}
  name: "vault-issuer-{{ . }}"
  {{- end }}
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
data:
  token: "{{ .Values.vault_token }}"
