ingress:
  tls:
    - hosts:
        - todo.devops.com
backend:
  repository: docker.pkg.github.com/Todo-Full-Stack-Deployment/sheplx/backend
  tag: b33d0cc7dff1dead7ae55e0c53e130bc46be1de1
frontend:
  repository: docker.pkg.github.com/Todo-Full-Stack-Deployment/sheplx/frontend
  tag: b33d0cc7dff1dead7ae55e0c53e130bc46be1de1
spec:
  replicas: 3
DBname:
  name: db
