ingress:
  tls:
    - hosts:
        - todo.devops.com
backend:
  repository: docker.pkg.github.com/Todo-Full-Stack-Deployment/sheplx/backend
  tag: 56b091cd7944c1d76af4f2c8e4dd4e167859fd43
frontend:
  repository: docker.pkg.github.com/Todo-Full-Stack-Deployment/sheplx/frontend
  tag: 56b091cd7944c1d76af4f2c8e4dd4e167859fd43
spec:
  replicas: 3
DBname:
  name: db
