name: TODO-BACKEND-CI
on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage
    paths:
      - 'backend/**'

env:
  BACKEND_IMAGE: backend

jobs:
  TODO-BACKEND-CI:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Changed Files In Backend Folder
        id: backend
        uses: tj-actions/changed-files@v35
        with:
          files: ${{ env.BACKEND_IMAGE }}/**

      - name: Changed Files
        if: steps.backend.outputs.any_changed == 'true'
        run: |
          echo "Changed Files: ${{ steps.backend.outputs.all_changed_files }}"

      - name: Build Backend Docker Image
        working-directory: backend/
        run: docker build -t $BACKEND_IMAGE .

      - name: Scan Backend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.BACKEND_IMAGE }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Log Into Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push Image Tag
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$BACKEND_IMAGE
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${GITHUB_SHA:0:7}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $BACKEND_IMAGE $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Helm Chart Values at Main
        if: ${{ github.ref == 'refs/heads/main'}} 
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: app-charts/values.yaml
          tag_keys: .backend.tag      
          tag_value: ${{ env.VERSION }}
          commit_branch: ${{ github.ref }}
          commit_tag: Todo-Main-Charts-V-${{ env.VERSION }}
          commit_message: "Backend update: Tag '${{ env.VERSION }}' added"
          
      - name: Update Helm Chart Values at Stage
        if: ${{ github.ref == 'refs/heads/stage'}} 
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: app-charts/values.yaml
          tag_keys: .backend.tag          
          tag_value: ${{ env.VERSION }}
          commit_branch: ${{ github.ref }}
          commit_tag: Todo-Stage-Charts-V-${{ env.VERSION }}
          commit_message: "Backend update: Tag '${{ env.VERSION }}' added"

      - name: Update Helm Chart Values at Dev
        if: ${{ github.ref == 'refs/heads/dev'}} 
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: app-charts/values.yaml
          tag_keys: .backend.tag          
          tag_value: ${{ env.VERSION }}
          commit_branch: ${{ github.ref }}
          commit_tag: Todo-Dev-Charts-V-${{ env.VERSION }}
          commit_message: "Backend update: Tag '${{ env.VERSION }}' added"
