name: TODO-FRONTEND-CI
on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage
    paths:
      - 'frontend/**'

env:
  FRONTEND_IMAGE: frontend

jobs:
  TODO-FRONTEND-CI:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Changed Files In Frontend Folder
        id: frontend
        uses: tj-actions/changed-files@v35
        with:
          files: ${{ env.FRONTEND_IMAGE }}/**

      - name: Changed Files
        if: steps.frontend.outputs.any_changed == 'true'
        run: |
          echo "Changed Files: ${{ steps.frontend.outputs.all_changed_files }}"

      - name: Build Frontend Docker Image
        working-directory: frontend/events
        run: docker build -t $FRONTEND_IMAGE .

      - name: Scan Frontend Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.FRONTEND_IMAGE }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Log Into Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push Image Tag
        id: tag
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$FRONTEND_IMAGE
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=${GITHUB_SHA:0:7}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $FRONTEND_IMAGE $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Helm Chart Values at Main
        if: ${{ github.ref == 'refs/heads/main'}} 
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: app-charts/values.yaml
          tag_keys: .frontend.tag      
          tag_value: ${{ env.VERSION }}
          commit_branch: ${{ github.ref }}
          commit_tag: Todo-Main-Charts-V-${{ env.VERSION }}
          commit_message: "Frontend update: Tag '${{ env.VERSION }}' added"
          
      - name: Update Helm Chart Values at Stage
        if: ${{ github.ref == 'refs/heads/stage'}} 
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: app-charts/values.yaml
          tag_keys: .frontend.tag          
          tag_value: ${{ env.VERSION }}
          commit_branch: ${{ github.ref }}
          commit_tag: Todo-Stage-Charts-V-${{ env.VERSION }}
          commit_message: "Frontend update: Tag '${{ env.VERSION }}' added"

      - name: Update Helm Chart Values at Dev
        if: ${{ github.ref == 'refs/heads/dev'}} 
        uses: Nextdoor/helm-set-image-tag-action@main
        with:
          values_files: app-charts/values.yaml
          tag_keys: .frontend.tag          
          tag_value: ${{ env.VERSION }}
          commit_branch: ${{ github.ref }}
          commit_tag: Todo-Dev-Charts-V-${{ env.VERSION }}
          commit_message: "Frontend update: Tag '${{ env.VERSION }}' added"