name: TODO-CI
on:
  push:
    paths:
      - 'backend/**'
      - 'frontend/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files in the backend folder
        id: backend
        uses: tj-actions/changed-files@v35
        with:
          files: backend/**
        run: |
          echo "List all the files that have changed in the backend folder: ${{ steps.backend.outputs.all_changed_files }}"

      - name: Get changed files in the frontend folder
        id: frontend
        uses: tj-actions/changed-files@v35
        with:
          files: frontend/**
        run: |
          echo "List all the files that have changed in the frontend folder: ${{ steps.frontend.outputs.all_changed_files }}"

      - name: Build backend Docker image
        if: steps.backend.outputs.any_changed == 'true'
        working-directory: backend/
        run: |
          docker build -t my-backend .
          echo "List all the files that have changed: ${{ steps.backend.outputs.all_changed_files }}"

      - name: Build frontend Docker image
        if: steps.frontend.outputs.any_changed == 'true'
        working-directory: frontend/
        run: |
          docker build -t my-frontend-image .
          echo "List all the files that have changed: ${{ steps.frontend.outputs.all_changed_files }}"

      # - name: Scan Backend Image
      #   if: ${{ github.event_path == 'backend/**' }}
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: $BACKEND_IMAGE
      #     format: table
      # -    
      #   name: Scan Frontend Image
      #   if: ${{ github.event_path == 'frontend/**' }}
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: $FRONTEND_IMAGE
      #     format: sarif
      # -
      #   name: Upload scan results to Security Tab
      #   if: ${{ github.event_path == 'backend/**' || github.event_path == 'frontend/**' }}
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'
      # -
      #   name: Log Into Registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      # -
      #   name: Push Backend Image Tag
      #   run: |
      #     if [[ ${{ github.event_path }} == "backend" ]]; then
      #       IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$BACKEND_IMAGE
      #       IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
      #       VERSION=$GITHUB_SHA
      #       echo IMAGE_ID=$IMAGE_ID
      #       echo VERSION=$GITHUB_SHA
      #       docker tag $BACKEND_IMAGE $IMAGE_ID:$VERSION
      #       docker push $IMAGE_ID:$VERSION
      #     fi
      # -
      #   name: Push Frontend Image Tag
      #   run: |
      #     if [[ ${{ github.event_path }} == "frontend" ]]; then
      #       IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$FRONTEND_IMAGE
      #       IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
      #       VERSION=$GITHUB_SHA
      #       echo IMAGE_ID=$IMAGE_ID
      #       echo VERSION=$GITHUB_SHA
      #       docker tag $FRONTEND_IMAGE $IMAGE_ID:$VERSION
      #       docker push $IMAGE_ID:$VERSION
      #     fi  
      # -        
      #   name: 'Updating Helm Charts values on branch main'
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: Nextdoor/helm-set-image-tag-action@main
      #   with:
      #     values_files: charts/values.yaml
      #     tag_keys: .backend.tag
      #     tag_value: ${{ github.sha }}
      #     commit_branch: ${{ github.ref }}
      #     commit_tag: ${{ github.ref }}-chart
      #     commit_message: Tag ${{ github.sha }} Updated On Charts !
      # -   
      #   name: 'Updating Helm Charts values on branch dev'
      #   if: ${{ github.ref == 'refs/heads/dev' }}
      #   uses: Nextdoor/helm-set-image-tag-action@main
      #   with:
      #     values_files: charts/values.yaml
      #     tag_keys: .backend.tag          
      #     tag_value: ${{ github.sha }}
      #     commit_branch: ${{ github.ref }}
      #     commit_tag: ${{ github.ref }}-chart
      #     commit_message: Tag ${{ github.sha }} Updated On Charts !
      # -   
      #   name: 'Updating Helm Charts values on branch release'
      #   if: ${{ github.ref == 'refs/heads/release' }}
      #   uses: Nextdoor/helm-set-image-tag-action@main
      #   with:
      #     values_files: charts/values.yaml
      #     tag_keys: .backend.tag          
      #     tag_value: ${{ github.sha }}
      #     commit_branch: ${{ github.ref }}
      #     commit_tag: ${{ github.ref }}-chart
      #     commit_message: Tag ${{ github.sha }} Updated On Charts !





# jobs:
#   build:
#     runs-on: ubuntu-latest  # windows-latest | macos-latest
#     name: Test changed-files
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

#       # Example 1
#       - name: Get changed files
#         id: changed-files
#         uses: tj-actions/changed-files@v35
        
#         # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
#         # with:
#         #   since_last_remote_commit: true 

#       - name: List all changed files
#         run: |
#           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
#             echo "$file was changed"
#           done

#       # Example 2
#       - name: Get changed files in the docs folder
#         id: changed-files-specific
#         uses: tj-actions/changed-files@v35
#         with:
#           files: docs/*.{js,html}  # Alternatively using: `docs/**` or `docs`

#       - name: Run step if any file(s) in the docs folder change
#         if: steps.changed-files-specific.outputs.any_changed == 'true'
#         run: |
#           echo "One or more files in the docs folder has changed."
#           echo "List all the files that have changed: ${{ steps.changed-files-specific.outputs.all_changed_files }}"